### PR TITLE
Fix IR compilation with latest versions of kotlin-react

### LINKED ISSUE #25: Incompatible with recent versions of kotlin-wrappers
This plugin isn't compatible with the latest `kotlin-react` or `kotin-react-legacy`.

This is the stacktrace when I try to compile a simple KotlinJS project:
```
e: java.lang.NullPointerException
	at com.bnorm.react.KnownClassSymbols$ReactPackage.<init>(KnownClassSymbols.kt:11)
	at com.bnorm.react.KnownClassSymbols.<init>(KnownClassSymbols.kt:9)
	at com.bnorm.react.KnownClassTypes.<init>(KnownClassTypes.kt:14)
	at com.bnorm.react.ReactFunctionCallTransformer.<init>(ReactFunctionCallTransformer.kt:84)
	at com.bnorm.react.ReactFunctionIrGenerationExtension.generate(ReactFunctionIrGenerationExtension.kt:29)
	at org.jetbrains.kotlin.ir.backend.js.KlibKt.generateModuleFragmentWithPlugins$lambda-26(klib.kt:456)
	at org.jetbrains.kotlin.psi2ir.Psi2IrTranslator.generateModuleFragment(Psi2IrTranslator.kt:88)
	at org.jetbrains.kotlin.ir.backend.js.KlibKt.generateModuleFragmentWithPlugins(klib.kt:461)
	at org.jetbrains.kotlin.ir.backend.js.KlibKt.generateKLib(klib.kt:189)
	at org.jetbrains.kotlin.ir.backend.js.KlibKt.generateKLib$default(klib.kt:122)
	at org.jetbrains.kotlin.cli.js.K2JsIrCompiler.doExecute(K2JsIrCompiler.kt:264)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:178)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:71)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:92)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at org.jetbrains.kotlin.incremental.IncrementalJsCompilerRunner.runCompiler(IncrementalJsCompilerRunner.kt:193)
	at org.jetbrains.kotlin.incremental.IncrementalJsCompilerRunner.runCompiler(IncrementalJsCompilerRunner.kt:78)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally(IncrementalCompilerRunner.kt:357)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally$default(IncrementalCompilerRunner.kt:299)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl$rebuild(IncrementalCompilerRunner.kt:118)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:169)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:80)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile$default(IncrementalCompilerRunner.kt:71)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execJsIncrementalCompiler(CompileServiceImpl.kt:564)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execJsIncrementalCompiler(CompileServiceImpl.kt:100)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1802)
	at jdk.internal.reflect.GeneratedMethodAccessor104.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

~~I tried to clone your project, make some patches but when after I run `publishToMavenLocal`, Gradle can't find my local plugin publication~~

### PR DESCRIPTION
**Pull request by DVDAndroid**
Fixes #25 

Sample compiles and runs fine ~~; however, please review it since Gradle can't find the plugin in my maven local repo~~

### CODE REVIEW

**Comment by bnorm** [comment]
@DVDAndroid Thanks so much for tackling this! I want to take a closer look at some of the changes - especially around the FC class - as I haven't kept up with the latest changes from kotlin-wrappers. But a quick glance looks good!

File: kotlin-react-function-plugin/src/main/kotlin/com/bnorm/react/KnownClassTypes.kt [hunk 1]
```diff
@@ -16,13 +16,7 @@ internal class KnownClassTypes(
...
   class ReactPackage(context: IrPluginContext, private val classes: KnownClassSymbols) {
     val Props = classes.react.Props.createType(false, emptyList())
-    fun FC(type: IrType = Props): IrSimpleType {
-      val typeAlias = classes.react.FC.owner.expandedType as IrSimpleType
-      return typeAlias.buildSimpleType {
-        arguments = listOf(type as IrTypeArgument)
-      }
-    }
-
+    val FC = classes.react.FC.createType(false, emptyList())
```
Comment (bnorm) [inline kotlin-react-function-plugin/src/main/kotlin/com/bnorm/react/KnownClassTypes.kt]: Does the `FC` type no longer have a type parameter?

File: sample/src/main/kotlin/com/bnorm/react/index.kt [hunk 2]
```diff
@@ -3,11 +3,16 @@
...
 
 fun main() {
   injectGlobal(styles.global)
-  render(document.getElementById("root")) { App() }
+
+  val container = document.createElement("div")
+  document.body!!.appendChild(container)
+
+  render(buildElement { App() }, container)
 }
```
Comment (bnorm) [inline sample/src/main/kotlin/com/bnorm/react/index.kt]: Why the need to create a new element rather than using `root` as before? Wouldn't `render(buildElement { App() }, document.getElementById("root"))` work?

File: sample/build.gradle.kts [hunk 3]
```diff
@@ -19,8 +19,8 @@ dependencies {
   implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.0")
   implementation("org.jetbrains.kotlinx:kotlinx-datetime:0.2.1")
 
-  implementation(enforcedPlatform("org.jetbrains.kotlin-wrappers:kotlin-wrappers-bom:0.0.1-pre.256-kotlin-1.5.31"))
-  implementation("org.jetbrains.kotlin-wrappers:kotlin-react-dom")
+  implementation(enforcedPlatform("org.jetbrains.kotlin-wrappers:kotlin-wrappers-bom:0.0.1-pre.286-kotlin-1.6.10"))
+  implementation("org.jetbrains.kotlin-wrappers:kotlin-react-dom-legacy")
```
Comment (bnorm) [inline sample/build.gradle.kts:23]: If this will eventually go away, would be great to switch to the non-legacy artifact in the sample. But that can be a follow up PR. I like keeping this PR just about compatibility.

File: kotlin-react-function-plugin/src/main/kotlin/com/bnorm/react/ReactFunctionCallTransformer.kt [hunk 4]
```diff
@@ -237,14 +237,14 @@ class ReactFunctionCallTransformer(
...
     // TODO type=@[ExtensionFunctionType]?
-    val lambdaType = context.irBuiltIns.function(2)
-      .createType(false, listOf(
-        classes.react.RBuilder as IrTypeArgument,
-        propsType as IrTypeArgument,
-        context.irBuiltIns.unitType as IrTypeArgument
-      ))
-
-    return irCall(functions.react.fc, classes.react.FC(propsType)).apply {
+    val lambdaType = context.irBuiltIns.functionN(2)
```
Comment (bnorm) [inline kotlin-react-function-plugin/src/main/kotlin/com/bnorm/react/ReactFunctionCallTransformer.kt:241]: I'm guessing this change is because of some change in the compiler?

**Review by bnorm — COMMENTED** [review]
What are the `kotlin-js-store/yarn.lock` files for? Accidental includes? Or are they something new for Kotlin/JS and could they be ignored?

File: kotlin-react-function-plugin/src/main/kotlin/com/bnorm/react/KnownClassTypes.kt (hunk 1 above)
Comment (DVDAndroid) [reply kotlin-react-function-plugin/src/main/kotlin/com/bnorm/react/KnownClassTypes.kt]: Missed it, fixed in latest commits

File: sample/src/main/kotlin/com/bnorm/react/index.kt (hunk 2 above)
Comment (DVDAndroid) [reply sample/src/main/kotlin/com/bnorm/react/index.kt]: I used the new syntax, but I reverted it to the legacy one in the latest commits

File: kotlin-react-function-plugin/src/main/kotlin/com/bnorm/react/ReactFunctionCallTransformer.kt (hunk 4 above)
Comment (DVDAndroid) [reply kotlin-react-function-plugin/src/main/kotlin/com/bnorm/react/ReactFunctionCallTransformer.kt:241]: When I updated to Kotlin 1.6, there were unresolved functions; I used IntelliJ auto complete to get the right methods to call, since there's no documentation

**Comment by DVDAndroid** [comment]
> What are the `kotlin-js-store/yarn.lock` files for? Accidental includes? Or are they something new for Kotlin/JS and could they be ignored?

New feature in Kotlin 1.6.10 ([KT-34014](https://youtrack.jetbrains.com/issue/KT-34014)), it's for security purposes. It should be committed to VCS

**Comment by DVDAndroid** [comment]
Btw, sample running and testing was a little tricky; I had to push to maven local `*-gradle` and `*-function` modules, replace `sample/build.gradle.kts` by adding the local pushed Gradle plugin to classpath and removing it from 'plugins` block, and add a manual dependency to `dependencies` block

I don't know if it's possible to reference a Gradle plugin by path

File: sample/build.gradle.kts (hunk 3 above)
Comment (DVDAndroid) [reply sample/build.gradle.kts:23]: [Here](https://github.com/JetBrains/kotlin-wrappers/blob/master/CHANGELOG.md) the new changes in kotlin-wrappers

Maybe there will need to be a rewrite of the library to support the new syntax.

**Comment by bnorm** [comment]
Thank you so much!
